### ISSUE TITLE
能告知下您的开发环境吗？

### ISSUE THREAD

**Issue by justbegin01** [kasumar/TweakForWeChatRedEnvelop#1]
我使用xcode7+theos+iosopendev 编译不能通过呀。

**Comment by raochuan** [comment]
xcode8.2.1编译不通过 有可能是theos没安装成功。

**Comment by kasumar** [comment]
我的是：Xcode5.0/6.4 + iOSOpenDev1.62
Xcode7.x/8.x版本我没试过，iOSOpenDev好久没更新了，有可能不行。
Xcode高版本的建议用Theos吧，这东西就是勾了几个微信的函数，和iOSOpenDev没啥关系
